const problems = [
  {
    title: "Sunday-night reporting hell",
    pain:
      "Your team rebuilds the same numbers every week, by hand, from screenshots, WhatsApp messages, and spreadsheets.",
    outcome:
      "We replace it with one source of truth — the same numbers, generated by themselves, emailed every Friday.",
  },
  {
    title: "Labour costs you can't explain",
    pain:
      "End of the month you know what you paid. You don't know what for, or whether you should have.",
    outcome:
      "Every shift, activity, and payment lands in the same system. Cost per kg, per phase, per crew — visible in a click.",
  },
  {
    title: "Decisions made with last week's data",
    pain:
      "By the time the data reaches the boardroom it's already wrong. You react to problems instead of seeing them coming.",
    outcome:
      "Operational data flows live. The same numbers your floor staff log show up on the dashboard within minutes.",
  },
];

export default function ProblemCards() {
  return (
    <section className="py-20 sm:py-28 bg-gray-50">
      <div className="max-w-6xl mx-auto px-6">
        <div className="max-w-2xl">
          <p className="text-sm font-medium text-blue-600 tracking-wide uppercase mb-3">
            What we hear, over and over
          </p>
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 tracking-tight">
            Three ways ops chaos shows up.
          </h2>
          <p className="mt-4 text-lg text-gray-500">
            Different industries, different vocabulary, same pattern. If two of these sound like
            your week, we should talk.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6">
          {problems.map((p) => (
            <article
              key={p.title}
              className="bg-white border border-gray-200 rounded-2xl p-6 flex flex-col"
            >
              <h3 className="text-base font-semibold text-gray-900 leading-tight">
                {p.title}
              </h3>
              <p className="mt-3 text-sm text-gray-600 leading-relaxed">{p.pain}</p>
              <div className="mt-4 pt-4 border-t border-gray-100">
                <p className="text-xs font-medium text-blue-600 uppercase tracking-wide mb-1.5">
                  What we replace it with
                </p>
                <p className="text-sm text-gray-900 leading-relaxed">{p.outcome}</p>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
